# Generated by Django 5.1.2 on 2024-11-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='common_matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gender', 'Gender'), ('religion', 'Religion'), ('caste', 'Caste'), ('profession', 'Profession'), ('education', 'Education'), ('location', 'Location'), ('language', 'Language'), ('marital_status', 'Marital_status')], max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
