# Generated by Django 5.1.2 on 2024-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_table', '0003_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
