# Generated by Django 5.1.2 on 2024-11-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
