# Generated by Django 5.1.2 on 2024-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_preference_created_at_preference_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='age',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='height',
            new_name='max_height',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='weight',
            new_name='max_weight',
        ),
        migrations.AddField(
            model_name='preference',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='height in centimeters(Cm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight in kilograms(Kg)', max_digits=5, null=True),
        ),
    ]
