# Generated by Django 5.1.2 on 2024-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_rename_age_preference_max_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='annual_income',
            new_name='max_annual_income',
        ),
        migrations.AddField(
            model_name='preference',
            name='min_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
