# Generated by Django 5.1.2 on 2024-11-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='heigth in centimeters(Cm)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='weight in kilograms(Kg)', max_digits=5),
        ),
    ]
