# Generated by Django 5.1.2 on 2024-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
